---
title: "R Notebook"
output: html_notebook
---

```{r}
linealmod <- lm(dataset$IPC ~ dataset$F+dataset$P1+dataset$P2+dataset$P3+dataset$P4+dataset$P5+dataset$P6+dataset$P7+dataset$P8+dataset$P9+dataset$P10+dataset$P11+dataset$P12+dataset$P13+dataset$P14+dataset$P15+dataset$P16+dataset$P17+dataset$P18+dataset$P19+dataset$P20+dataset$P21+dataset$P22+dataset$P23+dataset$P24+dataset$P25+dataset$P26+dataset$P27+dataset$P28+dataset$P29+dataset$P30+dataset$P31+dataset$P32+dataset$P33+dataset$P34+dataset$P35+dataset$P36+dataset$P37+dataset$P38+dataset$P39+dataset$P40+dataset$P41+dataset$P42+dataset$P43+dataset$P44+dataset$P45+dataset$P46+dataset$P47+dataset$P48+dataset$P49+dataset$P50+dataset$P51+dataset$P52+dataset$P53+dataset$P54+dataset$P55+dataset$P56+dataset$P57+dataset$P58+dataset$P59+dataset$P60+dataset$P61+dataset$P62+dataset$P63+dataset$P64+dataset$P65+dataset$P66+dataset$P67+dataset$P68+dataset$P69+dataset$P70+dataset$P71+dataset$P72+dataset$P73+dataset$P74+dataset$P75+dataset$P76+dataset$P77+dataset$P78+dataset$P79+dataset$P80+dataset$P81+dataset$P82+dataset$P83+dataset$P84+dataset$P85+dataset$P86+dataset$P87+dataset$P88+dataset$P89+dataset$P90+dataset$P91+dataset$P92+dataset$P93+dataset$P94+dataset$P95+dataset$P96+dataset$P97+dataset$P98+dataset$P99+dataset$P100+dataset$P101+dataset$P102+dataset$P103+dataset$P104+dataset$P105+dataset$P106+dataset$P107+dataset$P108+dataset$P109+dataset$P110+dataset$P111+dataset$P112+dataset$P113+dataset$P114+dataset$P115+dataset$P116+dataset$P117+dataset$P118+dataset$P119+dataset$P120+dataset$P121+dataset$P122+dataset$P123+dataset$P124+dataset$P125+dataset$P126+dataset$P127+dataset$P128+dataset$P129+dataset$P130+dataset$P131+dataset$P132+dataset$P133+dataset$P134+dataset$P135+dataset$P136+dataset$P137+dataset$P138+dataset$P139+dataset$P140+dataset$P141+dataset$P142+dataset$P143+dataset$P144+dataset$P145+dataset$P146+dataset$P147+dataset$P148+dataset$P149+dataset$P150+dataset$P151+dataset$P152+dataset$P153+dataset$P154+dataset$P155+dataset$P156+dataset$P157+dataset$P158+dataset$P159+dataset$P160+dataset$P161+dataset$P162+dataset$P163+dataset$P164+dataset$P165+dataset$P166+dataset$P167+dataset$P168+dataset$P169+dataset$P170+dataset$P171+dataset$P172+dataset$P173+dataset$P174+dataset$P175+dataset$P176+dataset$P177+dataset$P178+dataset$P179+dataset$P180+dataset$P181+dataset$P182+dataset$P183+dataset$P184+dataset$P185+dataset$P186+dataset$P187+dataset$P188+dataset$P189+dataset$P190+dataset$P191+dataset$P192+dataset$P193+dataset$P194+dataset$P195+dataset$P196+dataset$P197+dataset$P198+dataset$P199+dataset$P200+dataset$P201+dataset$P202+dataset$P203+dataset$P204+dataset$P205+dataset$P206+dataset$P207+dataset$P208+dataset$P209+dataset$P210+dataset$P211+dataset$P212+dataset$P213+dataset$P214+dataset$P215+dataset$P216+dataset$P217+dataset$P218+dataset$P219+dataset$P220+dataset$P221+dataset$P222+dataset$P223+dataset$P224+dataset$P225+dataset$P226+dataset$P227+dataset$P228+dataset$P229+dataset$P230+dataset$P231+dataset$P232+dataset$P233+dataset$P234+dataset$P235+dataset$P236+dataset$P237+dataset$P238+dataset$P239+dataset$P240+dataset$P241+dataset$P242+dataset$P243+dataset$P244+dataset$P245+dataset$P246+dataset$P247+dataset$P248+dataset$P249+dataset$P250+dataset$P251+dataset$P252+dataset$P253+dataset$P254+dataset$P255+dataset$P256+dataset$P257+dataset$P258+dataset$P259+dataset$P260+dataset$P261+dataset$P262+dataset$P263+dataset$P264+dataset$P265+dataset$P266+dataset$P267+dataset$P268+dataset$P269+dataset$P270+dataset$P271+dataset$P272+dataset$P273+dataset$P274+dataset$P275+dataset$P276+dataset$P277+dataset$P278+dataset$P279+dataset$P280+dataset$P281+dataset$P282+dataset$P283+dataset$P284+dataset$P285+dataset$P286+dataset$P287+dataset$P288+dataset$P289+dataset$P290+dataset$P291+dataset$P292+dataset$P293+dataset$P294+dataset$P295+dataset$P296+dataset$P297+dataset$P298+dataset$P299+dataset$P300+dataset$P301+dataset$P302+dataset$P303)
```
```{r}
summary(linealmod)
```